<?php

function customcontact_form_alter(&$form,&$form_state, $form_id) {
    if($form_id == 'contact_site_form'){
        $form['copy']['#type'] = "hidden";
        $form['copy']['#value'] = 1;
        $form['subject']['#type'] = 'hidden';
        $form['subject']['#value'] = "Feedback";
        print "<pre>";
        print_r($form);
        print "</pre>";
    }
    if($form_id =='recipe_node_form'){
        // $form['comment_settings']['#type'] = "hidden";
        // $form['options']['#type'] = "hidden";
        // $form['author']['#type'] = "hidden";
        // $form['revision_information']['#type'] = "hidden";

        $form['#after_build'][] = 'customcontact_after_build';

        // print "<pre>";
        // print_r($form);
        // print "</pre>";


    }
}

function customcontact_after_build($form, &$form_state){

    // $form['additional_settings']['#type'] = "hidden";

    // $form['additional_settings']['group']['#groups']['additional_settings'][0]['enabled']['#type'] = "hidden";

    // unset($form['additional_settings']);

    // print "<pre>";
    // print_r($form);
    // print "</pre>";

    return $form;
}

// function customcontact_form_recipe_node_form_alter(&$form, &$form_state, $form_id){
//         print "<pre>";
//         print_r($form_state);
//         print "</pre>";
// }
